set -g status-style                  "bg=#faf8f3,fg=#6e5e4a"
set -g status-left-style             "bg=#f0ede5,fg=#3a8a56,bold"
set -g status-right-style            "bg=#faf8f3,fg=#a07818"

set -g window-status-current-style   "fg=#c0613a,bold"
set -g window-status-current-format  " #I:#W "

set -g window-status-style           "fg=#9c8a72"
set -g window-status-format          " #I:#W "

set -g pane-border-style             "fg=#e8e0d0"
set -g pane-active-border-style      "fg=#c0613a"

set -g message-style                 "bg=#e8e0d0,fg=#2c2218"
set -g message-command-style         "bg=#e8e0d0,fg=#a07818"

set -g mode-style                    "bg=#d4c8b0,fg=#2c2218"

set -g clock-mode-colour             "#c0613a"
