prSections:
  - title: My PRs
    filters: is:open author:@me
    layout:
      author:
        hidden: true
      reviewDecision:
        hidden: false
      lines:
        hidden: false
  - title: Needs My Review
    filters: is:open review-requested:@me
    layout:
      author:
        hidden: false
      reviewDecision:
        hidden: false
      lines:
        hidden: false
  - title: Involved
    filters: is:open involves:@me -author:@me -review-requested:@me
    layout:
      author:
        hidden: false
      reviewDecision:
        hidden: false

issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me

defaults:
  prsLimit: 20
  issuesLimit: 20
  preview:
    open: true
    width: 60

keybindings:
  prs:
    - key: o
      command: >
        gh pr view {{.PrNumber}} --web --repo {{.RepoName}}
    - key: c
      command: >
        gh pr checkout {{.PrNumber}} --repo {{.RepoName}}
